# https://github.com/marketplace/actions/release-drafter

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Breaking'
    label: 'type: breaking'
  - title: 'New Features'
    label: 'type: feature'
  - title: 'Bug Fixes'
    label: 'type: fix'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Other'
    labels:
      - 'type: build'
      - 'type: chore'
      - 'type: ci'
      - 'type: style'
      - 'type: refactor'
      - 'type: perf'
      - 'type: test'

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: build'
      - 'type: chore'
      - 'type: ci'
      - 'type: docs'
      - 'type: style'
      - 'type: refactor'
      - 'type: perf'
      - 'type: test'

category-template: '**$TITLE**'

template: |
  $CHANGES

replacers:
  - search: '/(fix|feat|build|chore|ci|docs|style|refactor|perf|test)!?: /ig'
    replace: ''
